import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepagev1">HomepageV1</Link>
        </li>
        <li>
          <Link to="/homepagev2">HomepageV2</Link>
        </li>
        <li>
          <Link to="/homepagev3">HomepageV3</Link>
        </li>
        <li>
          <Link to="/categorieswithsidebar">CategorieswithSidebar</Link>
        </li>
        <li>
          <Link to="/productlist">ProductList</Link>
        </li>
        <li>
          <Link to="/productdetails">ProductDetails</Link>
        </li>
        <li>
          <Link to="/collectionlist">CollectionList</Link>
        </li>
        <li>
          <Link to="/collectiondetails">CollectionDetails</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/blogdetail">BlogDetail</Link>
        </li>
        <li>
          <Link to="/giftcard">GiftCard</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/searchpage">SearchPage</Link>
        </li>
        <li>
          <Link to="/contactpage">ContactPage</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
